### ISSUE TITLE
Fix homotypic grouping build exception

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/xcol#29]
> Fail to convert usage Tutcheria symplocifolia Merr. & F. P. Metcalf into a synonym of the non accepted name Pyrenaria microcarpa var. ovalifolia (H. L. Li) T. L. Ming & S. X. Yang [SYNONYM]
 
> INFO  [2023-07-03 13:07:00,040] life.catalogue.basgroup.HomotypicConsolidator: Consolidate homotypic group symplocifolia with 1 recombinations and basionym=SYNONYM SPECIES Tutcheria symplocifolia Merr. & F. P. Metcalf [59RB2 parentId=5R33S] with 0 duplicates in ACCEPTED FAMILY Theaceae Mirb. ex Ker Gawl. [H5S parent=625QY]
ERROR [2023-07-03 13:07:00,050] life.catalogue.concurrent.BackgroundJob: Error running XRelease job 47eaee3d-36ce-448b-a4ca-3a84541fe975
! java.lang.IllegalArgumentException: Fail to convert usage Tutcheria symplocifolia Merr. & F. P. Metcalf into a synonym of the non accepted name Pyrenaria microcarpa var. ovalifolia (H. L. Li) T. L. Ming & S. X. Yang [SYNONYM]
! at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
! at life.catalogue.basgroup.HomotypicConsolidator.convertToSynonym(HomotypicConsolidator.java:319)
! at life.catalogue.basgroup.HomotypicConsolidator.consolidate(HomotypicConsolidator.java:298)
! at life.catalogue.basgroup.HomotypicConsolidator.consolidate(HomotypicConsolidator.java:201)
! at life.catalogue.basgroup.HomotypicConsolidator.consolidate(HomotypicConsolidator.java:109)
! at life.catalogue.release.XRelease.finalWork(XRelease.java:165)
! at life.catalogue.release.AbstractProjectCopy.runWithLock(AbstractProjectCopy.java:148)
! at life.catalogue.concurrent.DatasetBlockingJob.execute(DatasetBlockingJob.java:85)
! at life.catalogue.concurrent.BackgroundJob.run(BackgroundJob.java:135)
! at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
! at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
! at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
! at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
! at java.base/java.lang.Thread.run(Thread.java:829)
ERROR [2023-07-03 13:07:00,051] life.catalogue.release.AbstractProjectCopy: Error releasing extended project 3 into dataset 9908
! java.lang.IllegalArgumentException: Fail to convert usage Tutcheria symplocifolia Merr. & F. P. Metcalf into a synonym of the non accepted name Pyrenaria microcarpa var. ovalifolia (H. L. Li) T. L. Ming & S. X. Yang [SYNONYM]
! at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
! at life.catalogue.basgroup.HomotypicConsolidator.convertToSynonym(HomotypicConsolidator.java:319)
! at life.catalogue.basgroup.HomotypicConsolidator.consolidate(HomotypicConsolidator.java:298)
! at life.catalogue.basgroup.HomotypicConsolidator.consolidate(HomotypicConsolidator.java:201)
! at life.catalogue.basgroup.HomotypicConsolidator.consolidate(HomotypicConsolidator.java:109)
! at life.catalogue.release.XRelease.finalWork(XRelease.java:165)
! at life.catalogue.release.AbstractProjectCopy.runWithLock(AbstractProjectCopy.java:148)
! at life.catalogue.concurrent.DatasetBlockingJob.execute(DatasetBlockingJob.java:85)
! at life.catalogue.concurrent.BackgroundJob.run(BackgroundJob.java:135)
! at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
! at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
! at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
! at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
! at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by mdoering** [comment]
The merge actually updated synonyms and made some synonyms having another synonym as the accepted which is forbidden. Fixed in https://github.com/CatalogueOfLife/backend/commit/94e4b257c27d4f9a394b5cf59a822da5594ffd9f
